### ISSUE TITLE
建议增加对换行的支持

### ISSUE THREAD

**Issue by Hsiao-Feng** [Niefee/textConversion#1]
已经在Fork后增加了对A-Z a-z 0-9的支持，但不知道怎么增加对换行的支持。

**Comment by Niefee** [comment]
最直接快捷的方式是添加`<br/>`

**Comment by LeaderAndMaster** [comment]
请问那个词库您是怎么弄的啊。

**Comment by Hsiao-Feng** [comment]
a.js中的第4、9、14行，文件有注释说明是那个语言。
应该是一个对应一个吧。

**Comment by Niefee** [comment]
这个只是当时用来玩玩，现在很少有人用火星文了。我其实的想法是跟另一个项目一起做的，用文字转火星文然后生成一个图片做微信表情包生成器，思路已经有了，但没什么时间做。

**Comment by Hsiao-Feng** [comment]
火星文现在的用途是用于防屏蔽关键字2333

**Comment by Niefee** [comment]
事啊，蛋野优人用童音字。（是啊，但也有人用同音字） @KaedeShinoda

**Comment by Hsiao-Feng** [comment]
汏哆薮亾嘟洎帶焱暒妏啝瀿軆啭換。

**Comment by Niefee** [comment]
火星文或者同音字，都看得挺辛苦的。
